-- Script para corregir la numeraci¾n de filas completamente
-- Actualiza rowLabel, label, y metadata.canvas.label

-- ========== VIP ==========
UPDATE Seat SET rowLabel = CONCAT('TEMP_', rowLabel) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'VIP%';

UPDATE Seat SET rowLabel = '8' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'VIP%' AND rowLabel = 'TEMP_1';
UPDATE Seat SET rowLabel = '7' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'VIP%' AND rowLabel = 'TEMP_2';
UPDATE Seat SET rowLabel = '6' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'VIP%' AND rowLabel = 'TEMP_3';
UPDATE Seat SET rowLabel = '5' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'VIP%' AND rowLabel = 'TEMP_4';
UPDATE Seat SET rowLabel = '4' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'VIP%' AND rowLabel = 'TEMP_5';
UPDATE Seat SET rowLabel = '3' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'VIP%' AND rowLabel = 'TEMP_6';
UPDATE Seat SET rowLabel = '2' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'VIP%' AND rowLabel = 'TEMP_7';
UPDATE Seat SET rowLabel = '1' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'VIP%' AND rowLabel = 'TEMP_8';

-- Actualizar label (VC-1-23 -> VC-8-23, etc)
UPDATE Seat SET label = CONCAT('VC-', '8', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'VIP Central' AND rowLabel = '8' AND label LIKE 'VC-1-%';
UPDATE Seat SET label = CONCAT('VD-', '8', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'VIP Derecha' AND rowLabel = '8' AND label LIKE 'VD-1-%';
UPDATE Seat SET label = CONCAT('VI-', '8', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'VIP Izquierda' AND rowLabel = '8' AND label LIKE 'VI-1-%';
UPDATE Seat SET label = CONCAT('VC-', '7', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'VIP Central' AND rowLabel = '7' AND label LIKE 'VC-2-%';
UPDATE Seat SET label = CONCAT('VD-', '7', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'VIP Derecha' AND rowLabel = '7' AND label LIKE 'VD-2-%';
UPDATE Seat SET label = CONCAT('VI-', '7', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'VIP Izquierda' AND rowLabel = '7' AND label LIKE 'VI-2-%';
UPDATE Seat SET label = CONCAT('VC-', '6', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'VIP Central' AND rowLabel = '6' AND label LIKE 'VC-3-%';
UPDATE Seat SET label = CONCAT('VD-', '6', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'VIP Derecha' AND rowLabel = '6' AND label LIKE 'VD-3-%';
UPDATE Seat SET label = CONCAT('VI-', '6', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'VIP Izquierda' AND rowLabel = '6' AND label LIKE 'VI-3-%';
UPDATE Seat SET label = CONCAT('VC-', '5', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'VIP Central' AND rowLabel = '5' AND label LIKE 'VC-4-%';
UPDATE Seat SET label = CONCAT('VD-', '5', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'VIP Derecha' AND rowLabel = '5' AND label LIKE 'VD-4-%';
UPDATE Seat SET label = CONCAT('VI-', '5', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'VIP Izquierda' AND rowLabel = '5' AND label LIKE 'VI-4-%';
UPDATE Seat SET label = CONCAT('VC-', '4', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'VIP Central' AND rowLabel = '4' AND label LIKE 'VC-5-%';
UPDATE Seat SET label = CONCAT('VD-', '4', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'VIP Derecha' AND rowLabel = '4' AND label LIKE 'VD-5-%';
UPDATE Seat SET label = CONCAT('VI-', '4', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'VIP Izquierda' AND rowLabel = '4' AND label LIKE 'VI-5-%';
UPDATE Seat SET label = CONCAT('VC-', '3', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'VIP Central' AND rowLabel = '3' AND label LIKE 'VC-6-%';
UPDATE Seat SET label = CONCAT('VD-', '3', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'VIP Derecha' AND rowLabel = '3' AND label LIKE 'VD-6-%';
UPDATE Seat SET label = CONCAT('VI-', '3', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'VIP Izquierda' AND rowLabel = '3' AND label LIKE 'VI-6-%';
UPDATE Seat SET label = CONCAT('VC-', '2', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'VIP Central' AND rowLabel = '2' AND label LIKE 'VC-7-%';
UPDATE Seat SET label = CONCAT('VD-', '2', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'VIP Derecha' AND rowLabel = '2' AND label LIKE 'VD-7-%';
UPDATE Seat SET label = CONCAT('VI-', '2', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'VIP Izquierda' AND rowLabel = '2' AND label LIKE 'VI-7-%';
UPDATE Seat SET label = CONCAT('VC-', '1', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'VIP Central' AND rowLabel = '1' AND label LIKE 'VC-8-%';
UPDATE Seat SET label = CONCAT('VD-', '1', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'VIP Derecha' AND rowLabel = '1' AND label LIKE 'VD-8-%';
UPDATE Seat SET label = CONCAT('VI-', '1', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'VIP Izquierda' AND rowLabel = '1' AND label LIKE 'VI-8-%';

-- Actualizar metadata.canvas.label
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('8', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'VIP%' AND rowLabel = '8';
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('7', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'VIP%' AND rowLabel = '7';
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('6', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'VIP%' AND rowLabel = '6';
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('5', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'VIP%' AND rowLabel = '5';
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('4', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'VIP%' AND rowLabel = '4';
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('3', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'VIP%' AND rowLabel = '3';
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('2', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'VIP%' AND rowLabel = '2';
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('1', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'VIP%' AND rowLabel = '1';

-- ========== PLUS ==========
UPDATE Seat SET rowLabel = CONCAT('TEMP_', rowLabel) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PLUS%';

UPDATE Seat SET rowLabel = 'P' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PLUS%' AND rowLabel = 'TEMP_A';
UPDATE Seat SET rowLabel = 'O' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PLUS%' AND rowLabel = 'TEMP_B';
UPDATE Seat SET rowLabel = 'N' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PLUS%' AND rowLabel = 'TEMP_C';
UPDATE Seat SET rowLabel = 'M' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PLUS%' AND rowLabel = 'TEMP_D';
UPDATE Seat SET rowLabel = 'L' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PLUS%' AND rowLabel = 'TEMP_E';
UPDATE Seat SET rowLabel = 'K' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PLUS%' AND rowLabel = 'TEMP_F';
UPDATE Seat SET rowLabel = 'J' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PLUS%' AND rowLabel = 'TEMP_G';
UPDATE Seat SET rowLabel = 'I' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PLUS%' AND rowLabel = 'TEMP_H';
UPDATE Seat SET rowLabel = 'H' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PLUS%' AND rowLabel = 'TEMP_I';
UPDATE Seat SET rowLabel = 'G' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PLUS%' AND rowLabel = 'TEMP_J';
UPDATE Seat SET rowLabel = 'F' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PLUS%' AND rowLabel = 'TEMP_K';
UPDATE Seat SET rowLabel = 'E' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PLUS%' AND rowLabel = 'TEMP_L';
UPDATE Seat SET rowLabel = 'D' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PLUS%' AND rowLabel = 'TEMP_M';
UPDATE Seat SET rowLabel = 'C' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PLUS%' AND rowLabel = 'TEMP_N';
UPDATE Seat SET rowLabel = 'B' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PLUS%' AND rowLabel = 'TEMP_O';
UPDATE Seat SET rowLabel = 'A' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PLUS%' AND rowLabel = 'TEMP_P';

-- Actualizar label (PC-A-23 -> PC-P-23, etc)
UPDATE Seat SET label = CONCAT('PC-', 'P', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Central' AND rowLabel = 'P' AND label LIKE 'PC-A-%';
UPDATE Seat SET label = CONCAT('PD-', 'P', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Derecha' AND rowLabel = 'P' AND label LIKE 'PD-A-%';
UPDATE Seat SET label = CONCAT('PI-', 'P', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Izquierda' AND rowLabel = 'P' AND label LIKE 'PI-A-%';
UPDATE Seat SET label = CONCAT('PC-', 'O', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Central' AND rowLabel = 'O' AND label LIKE 'PC-B-%';
UPDATE Seat SET label = CONCAT('PD-', 'O', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Derecha' AND rowLabel = 'O' AND label LIKE 'PD-B-%';
UPDATE Seat SET label = CONCAT('PI-', 'O', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Izquierda' AND rowLabel = 'O' AND label LIKE 'PI-B-%';
UPDATE Seat SET label = CONCAT('PC-', 'N', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Central' AND rowLabel = 'N' AND label LIKE 'PC-C-%';
UPDATE Seat SET label = CONCAT('PD-', 'N', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Derecha' AND rowLabel = 'N' AND label LIKE 'PD-C-%';
UPDATE Seat SET label = CONCAT('PI-', 'N', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Izquierda' AND rowLabel = 'N' AND label LIKE 'PI-C-%';
UPDATE Seat SET label = CONCAT('PC-', 'M', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Central' AND rowLabel = 'M' AND label LIKE 'PC-D-%';
UPDATE Seat SET label = CONCAT('PD-', 'M', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Derecha' AND rowLabel = 'M' AND label LIKE 'PD-D-%';
UPDATE Seat SET label = CONCAT('PI-', 'M', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Izquierda' AND rowLabel = 'M' AND label LIKE 'PI-D-%';
UPDATE Seat SET label = CONCAT('PC-', 'L', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Central' AND rowLabel = 'L' AND label LIKE 'PC-E-%';
UPDATE Seat SET label = CONCAT('PD-', 'L', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Derecha' AND rowLabel = 'L' AND label LIKE 'PD-E-%';
UPDATE Seat SET label = CONCAT('PI-', 'L', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Izquierda' AND rowLabel = 'L' AND label LIKE 'PI-E-%';
UPDATE Seat SET label = CONCAT('PC-', 'K', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Central' AND rowLabel = 'K' AND label LIKE 'PC-F-%';
UPDATE Seat SET label = CONCAT('PD-', 'K', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Derecha' AND rowLabel = 'K' AND label LIKE 'PD-F-%';
UPDATE Seat SET label = CONCAT('PI-', 'K', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Izquierda' AND rowLabel = 'K' AND label LIKE 'PI-F-%';
UPDATE Seat SET label = CONCAT('PC-', 'J', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Central' AND rowLabel = 'J' AND label LIKE 'PC-G-%';
UPDATE Seat SET label = CONCAT('PD-', 'J', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Derecha' AND rowLabel = 'J' AND label LIKE 'PD-G-%';
UPDATE Seat SET label = CONCAT('PI-', 'J', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Izquierda' AND rowLabel = 'J' AND label LIKE 'PI-G-%';
UPDATE Seat SET label = CONCAT('PC-', 'I', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Central' AND rowLabel = 'I' AND label LIKE 'PC-H-%';
UPDATE Seat SET label = CONCAT('PD-', 'I', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Derecha' AND rowLabel = 'I' AND label LIKE 'PD-H-%';
UPDATE Seat SET label = CONCAT('PI-', 'I', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Izquierda' AND rowLabel = 'I' AND label LIKE 'PI-H-%';
UPDATE Seat SET label = CONCAT('PC-', 'H', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Central' AND rowLabel = 'H' AND label LIKE 'PC-I-%';
UPDATE Seat SET label = CONCAT('PD-', 'H', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Derecha' AND rowLabel = 'H' AND label LIKE 'PD-I-%';
UPDATE Seat SET label = CONCAT('PI-', 'H', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Izquierda' AND rowLabel = 'H' AND label LIKE 'PI-I-%';
UPDATE Seat SET label = CONCAT('PC-', 'G', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Central' AND rowLabel = 'G' AND label LIKE 'PC-J-%';
UPDATE Seat SET label = CONCAT('PD-', 'G', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Derecha' AND rowLabel = 'G' AND label LIKE 'PD-J-%';
UPDATE Seat SET label = CONCAT('PI-', 'G', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Izquierda' AND rowLabel = 'G' AND label LIKE 'PI-J-%';
UPDATE Seat SET label = CONCAT('PC-', 'F', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Central' AND rowLabel = 'F' AND label LIKE 'PC-K-%';
UPDATE Seat SET label = CONCAT('PD-', 'F', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Derecha' AND rowLabel = 'F' AND label LIKE 'PD-K-%';
UPDATE Seat SET label = CONCAT('PI-', 'F', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Izquierda' AND rowLabel = 'F' AND label LIKE 'PI-K-%';
UPDATE Seat SET label = CONCAT('PC-', 'E', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Central' AND rowLabel = 'E' AND label LIKE 'PC-L-%';
UPDATE Seat SET label = CONCAT('PD-', 'E', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Derecha' AND rowLabel = 'E' AND label LIKE 'PD-L-%';
UPDATE Seat SET label = CONCAT('PI-', 'E', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Izquierda' AND rowLabel = 'E' AND label LIKE 'PI-L-%';
UPDATE Seat SET label = CONCAT('PC-', 'D', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Central' AND rowLabel = 'D' AND label LIKE 'PC-M-%';
UPDATE Seat SET label = CONCAT('PD-', 'D', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Derecha' AND rowLabel = 'D' AND label LIKE 'PD-M-%';
UPDATE Seat SET label = CONCAT('PI-', 'D', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Izquierda' AND rowLabel = 'D' AND label LIKE 'PI-M-%';
UPDATE Seat SET label = CONCAT('PC-', 'C', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Central' AND rowLabel = 'C' AND label LIKE 'PC-N-%';
UPDATE Seat SET label = CONCAT('PD-', 'C', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Derecha' AND rowLabel = 'C' AND label LIKE 'PD-N-%';
UPDATE Seat SET label = CONCAT('PI-', 'C', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Izquierda' AND rowLabel = 'C' AND label LIKE 'PI-N-%';
UPDATE Seat SET label = CONCAT('PC-', 'B', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Central' AND rowLabel = 'B' AND label LIKE 'PC-O-%';
UPDATE Seat SET label = CONCAT('PD-', 'B', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Derecha' AND rowLabel = 'B' AND label LIKE 'PD-O-%';
UPDATE Seat SET label = CONCAT('PI-', 'B', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Izquierda' AND rowLabel = 'B' AND label LIKE 'PI-O-%';
UPDATE Seat SET label = CONCAT('PC-', 'A', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Central' AND rowLabel = 'A' AND label LIKE 'PC-P-%';
UPDATE Seat SET label = CONCAT('PD-', 'A', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Derecha' AND rowLabel = 'A' AND label LIKE 'PD-P-%';
UPDATE Seat SET label = CONCAT('PI-', 'A', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PLUS Izquierda' AND rowLabel = 'A' AND label LIKE 'PI-P-%';

-- Actualizar metadata.canvas.label
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('P', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PLUS%' AND rowLabel = 'P';
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('O', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PLUS%' AND rowLabel = 'O';
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('N', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PLUS%' AND rowLabel = 'N';
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('M', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PLUS%' AND rowLabel = 'M';
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('L', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PLUS%' AND rowLabel = 'L';
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('K', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PLUS%' AND rowLabel = 'K';
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('J', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PLUS%' AND rowLabel = 'J';
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('I', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PLUS%' AND rowLabel = 'I';
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('H', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PLUS%' AND rowLabel = 'H';
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('G', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PLUS%' AND rowLabel = 'G';
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('F', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PLUS%' AND rowLabel = 'F';
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('E', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PLUS%' AND rowLabel = 'E';
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('D', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PLUS%' AND rowLabel = 'D';
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('C', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PLUS%' AND rowLabel = 'C';
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('B', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PLUS%' AND rowLabel = 'B';
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('A', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PLUS%' AND rowLabel = 'A';

-- ========== PREFERENTE ==========
UPDATE Seat SET rowLabel = CONCAT('TEMP_', rowLabel) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PREFERENTE%';

UPDATE Seat SET rowLabel = 'P' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PREFERENTE%' AND rowLabel = 'TEMP_A';
UPDATE Seat SET rowLabel = 'O' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PREFERENTE%' AND rowLabel = 'TEMP_B';
UPDATE Seat SET rowLabel = 'N' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PREFERENTE%' AND rowLabel = 'TEMP_C';
UPDATE Seat SET rowLabel = 'M' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PREFERENTE%' AND rowLabel = 'TEMP_D';
UPDATE Seat SET rowLabel = 'L' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PREFERENTE%' AND rowLabel = 'TEMP_E';
UPDATE Seat SET rowLabel = 'K' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PREFERENTE%' AND rowLabel = 'TEMP_F';
UPDATE Seat SET rowLabel = 'J' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PREFERENTE%' AND rowLabel = 'TEMP_G';
UPDATE Seat SET rowLabel = 'I' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PREFERENTE%' AND rowLabel = 'TEMP_H';
UPDATE Seat SET rowLabel = 'H' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PREFERENTE%' AND rowLabel = 'TEMP_I';
UPDATE Seat SET rowLabel = 'G' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PREFERENTE%' AND rowLabel = 'TEMP_J';
UPDATE Seat SET rowLabel = 'F' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PREFERENTE%' AND rowLabel = 'TEMP_K';
UPDATE Seat SET rowLabel = 'E' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PREFERENTE%' AND rowLabel = 'TEMP_L';
UPDATE Seat SET rowLabel = 'D' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PREFERENTE%' AND rowLabel = 'TEMP_M';
UPDATE Seat SET rowLabel = 'C' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PREFERENTE%' AND rowLabel = 'TEMP_N';
UPDATE Seat SET rowLabel = 'B' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PREFERENTE%' AND rowLabel = 'TEMP_O';
UPDATE Seat SET rowLabel = 'A' WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PREFERENTE%' AND rowLabel = 'TEMP_P';

-- Actualizar label (PRC-A-23 -> PRC-P-23, etc)
UPDATE Seat SET label = CONCAT('PRC-', 'P', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Central' AND rowLabel = 'P' AND label LIKE 'PRC-A-%';
UPDATE Seat SET label = CONCAT('PRD-', 'P', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Derecha' AND rowLabel = 'P' AND label LIKE 'PRD-A-%';
UPDATE Seat SET label = CONCAT('PRI-', 'P', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Izquierda' AND rowLabel = 'P' AND label LIKE 'PRI-A-%';
UPDATE Seat SET label = CONCAT('PRC-', 'O', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Central' AND rowLabel = 'O' AND label LIKE 'PRC-B-%';
UPDATE Seat SET label = CONCAT('PRD-', 'O', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Derecha' AND rowLabel = 'O' AND label LIKE 'PRD-B-%';
UPDATE Seat SET label = CONCAT('PRI-', 'O', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Izquierda' AND rowLabel = 'O' AND label LIKE 'PRI-B-%';
UPDATE Seat SET label = CONCAT('PRC-', 'N', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Central' AND rowLabel = 'N' AND label LIKE 'PRC-C-%';
UPDATE Seat SET label = CONCAT('PRD-', 'N', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Derecha' AND rowLabel = 'N' AND label LIKE 'PRD-C-%';
UPDATE Seat SET label = CONCAT('PRI-', 'N', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Izquierda' AND rowLabel = 'N' AND label LIKE 'PRI-C-%';
UPDATE Seat SET label = CONCAT('PRC-', 'M', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Central' AND rowLabel = 'M' AND label LIKE 'PRC-D-%';
UPDATE Seat SET label = CONCAT('PRD-', 'M', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Derecha' AND rowLabel = 'M' AND label LIKE 'PRD-D-%';
UPDATE Seat SET label = CONCAT('PRI-', 'M', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Izquierda' AND rowLabel = 'M' AND label LIKE 'PRI-D-%';
UPDATE Seat SET label = CONCAT('PRC-', 'L', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Central' AND rowLabel = 'L' AND label LIKE 'PRC-E-%';
UPDATE Seat SET label = CONCAT('PRD-', 'L', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Derecha' AND rowLabel = 'L' AND label LIKE 'PRD-E-%';
UPDATE Seat SET label = CONCAT('PRI-', 'L', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Izquierda' AND rowLabel = 'L' AND label LIKE 'PRI-E-%';
UPDATE Seat SET label = CONCAT('PRC-', 'K', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Central' AND rowLabel = 'K' AND label LIKE 'PRC-F-%';
UPDATE Seat SET label = CONCAT('PRD-', 'K', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Derecha' AND rowLabel = 'K' AND label LIKE 'PRD-F-%';
UPDATE Seat SET label = CONCAT('PRI-', 'K', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Izquierda' AND rowLabel = 'K' AND label LIKE 'PRI-F-%';
UPDATE Seat SET label = CONCAT('PRC-', 'J', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Central' AND rowLabel = 'J' AND label LIKE 'PRC-G-%';
UPDATE Seat SET label = CONCAT('PRD-', 'J', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Derecha' AND rowLabel = 'J' AND label LIKE 'PRD-G-%';
UPDATE Seat SET label = CONCAT('PRI-', 'J', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Izquierda' AND rowLabel = 'J' AND label LIKE 'PRI-G-%';
UPDATE Seat SET label = CONCAT('PRC-', 'I', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Central' AND rowLabel = 'I' AND label LIKE 'PRC-H-%';
UPDATE Seat SET label = CONCAT('PRD-', 'I', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Derecha' AND rowLabel = 'I' AND label LIKE 'PRD-H-%';
UPDATE Seat SET label = CONCAT('PRI-', 'I', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Izquierda' AND rowLabel = 'I' AND label LIKE 'PRI-H-%';
UPDATE Seat SET label = CONCAT('PRC-', 'H', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Central' AND rowLabel = 'H' AND label LIKE 'PRC-I-%';
UPDATE Seat SET label = CONCAT('PRD-', 'H', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Derecha' AND rowLabel = 'H' AND label LIKE 'PRD-I-%';
UPDATE Seat SET label = CONCAT('PRI-', 'H', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Izquierda' AND rowLabel = 'H' AND label LIKE 'PRI-I-%';
UPDATE Seat SET label = CONCAT('PRC-', 'G', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Central' AND rowLabel = 'G' AND label LIKE 'PRC-J-%';
UPDATE Seat SET label = CONCAT('PRD-', 'G', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Derecha' AND rowLabel = 'G' AND label LIKE 'PRD-J-%';
UPDATE Seat SET label = CONCAT('PRI-', 'G', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Izquierda' AND rowLabel = 'G' AND label LIKE 'PRI-J-%';
UPDATE Seat SET label = CONCAT('PRC-', 'F', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Central' AND rowLabel = 'F' AND label LIKE 'PRC-K-%';
UPDATE Seat SET label = CONCAT('PRD-', 'F', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Derecha' AND rowLabel = 'F' AND label LIKE 'PRD-K-%';
UPDATE Seat SET label = CONCAT('PRI-', 'F', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Izquierda' AND rowLabel = 'F' AND label LIKE 'PRI-K-%';
UPDATE Seat SET label = CONCAT('PRC-', 'E', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Central' AND rowLabel = 'E' AND label LIKE 'PRC-L-%';
UPDATE Seat SET label = CONCAT('PRD-', 'E', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Derecha' AND rowLabel = 'E' AND label LIKE 'PRD-L-%';
UPDATE Seat SET label = CONCAT('PRI-', 'E', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Izquierda' AND rowLabel = 'E' AND label LIKE 'PRI-L-%';
UPDATE Seat SET label = CONCAT('PRC-', 'D', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Central' AND rowLabel = 'D' AND label LIKE 'PRC-M-%';
UPDATE Seat SET label = CONCAT('PRD-', 'D', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Derecha' AND rowLabel = 'D' AND label LIKE 'PRD-M-%';
UPDATE Seat SET label = CONCAT('PRI-', 'D', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Izquierda' AND rowLabel = 'D' AND label LIKE 'PRI-M-%';
UPDATE Seat SET label = CONCAT('PRC-', 'C', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Central' AND rowLabel = 'C' AND label LIKE 'PRC-N-%';
UPDATE Seat SET label = CONCAT('PRD-', 'C', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Derecha' AND rowLabel = 'C' AND label LIKE 'PRD-N-%';
UPDATE Seat SET label = CONCAT('PRI-', 'C', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Izquierda' AND rowLabel = 'C' AND label LIKE 'PRI-N-%';
UPDATE Seat SET label = CONCAT('PRC-', 'B', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Central' AND rowLabel = 'B' AND label LIKE 'PRC-O-%';
UPDATE Seat SET label = CONCAT('PRD-', 'B', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Derecha' AND rowLabel = 'B' AND label LIKE 'PRD-O-%';
UPDATE Seat SET label = CONCAT('PRI-', 'B', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Izquierda' AND rowLabel = 'B' AND label LIKE 'PRI-O-%';
UPDATE Seat SET label = CONCAT('PRC-', 'A', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Central' AND rowLabel = 'A' AND label LIKE 'PRC-P-%';
UPDATE Seat SET label = CONCAT('PRD-', 'A', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Derecha' AND rowLabel = 'A' AND label LIKE 'PRD-P-%';
UPDATE Seat SET label = CONCAT('PRI-', 'A', '-', SUBSTRING_INDEX(label, '-', -1)) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) = 'PREFERENTE Izquierda' AND rowLabel = 'A' AND label LIKE 'PRI-P-%';

-- Actualizar metadata.canvas.label
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('P', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PREFERENTE%' AND rowLabel = 'P';
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('O', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PREFERENTE%' AND rowLabel = 'O';
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('N', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PREFERENTE%' AND rowLabel = 'N';
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('M', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PREFERENTE%' AND rowLabel = 'M';
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('L', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PREFERENTE%' AND rowLabel = 'L';
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('K', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PREFERENTE%' AND rowLabel = 'K';
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('J', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PREFERENTE%' AND rowLabel = 'J';
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('I', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PREFERENTE%' AND rowLabel = 'I';
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('H', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PREFERENTE%' AND rowLabel = 'H';
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('G', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PREFERENTE%' AND rowLabel = 'G';
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('F', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PREFERENTE%' AND rowLabel = 'F';
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('E', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PREFERENTE%' AND rowLabel = 'E';
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('D', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PREFERENTE%' AND rowLabel = 'D';
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('C', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PREFERENTE%' AND rowLabel = 'C';
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('B', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PREFERENTE%' AND rowLabel = 'B';
UPDATE Seat SET metadata = JSON_SET(metadata, '$.canvas.label', CONCAT('A', '-', SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.canvas.label')), '-', -1))) WHERE layoutId = 'ad44b249-13ad-4c51-b1ff-f73ce9b80c9b' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.sectionName')) LIKE 'PREFERENTE%' AND rowLabel = 'A';
